### ISSUE TITLE
Docker error loading agent.yml config file

### ISSUE THREAD

**Issue by megacorvega** [Cubxity/UnifiedMetrics#36]
I am attempting to run the Grafana docker image from the wiki guide, but the image is stuck constantly restarting with this error

`2021-08-17T16:55:04.057681333Z 2021-08-17 16:55:04.057346 I | error loading config file /etc/agent-config/agent.yml: error reading config file: open /etc/agent-config/agent.yml: not a directory`

I attempted to create that directory in `etc` but I keep getting the error. Any ideas?

**Comment by Cubxity** [comment]
You need to bind the config file using volume mounts

**Comment by megacorvega** [comment]
I see. I guess I'm not familiar enough with docker. How would I do that?

**Comment by Cubxity** [comment]
Can you show the commands/files you have used?

**Comment by megacorvega** [comment]
I just followed the [provided Grafana Docker tutorial](https://github.com/Cubxity/UnifiedMetrics/wiki/Grafana-Agent-With-Docker) for the `agent.yml` and `

But after creating the network I just ran the container with `docker-compose up -d --remove-orphans`

I also gave my user permission of the `.docker` folder with `sudo chown -R $USER ~/.docker`

**Comment by Cubxity** [comment]
Can you just show me the files you have?

**Comment by megacorvega** [comment]
No problem

```
prometheus:
  global:
    scrape_interval: 5s
  configs:
    - name: minecraft
      host_filter: false
      scrape_configs:
        - job_name: minecraft_scrape
          static_configs:
            # Put your server's IP here
            - targets: [ "192.168.0.33:9100" ]
              # Feel free to add any labels here
              labels:
                node: "node-1"
      remote_write:
        # Create an account at https://grafana.com/ and create an organization.
        # Put Prometheus remote write credentials here. Make sure to update the push URL to match yours.
        - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
          # Create an API key with write scope on Grafana Cloud
          basic_auth:
            username: <user-name-from-prom-data-source>
            password: configured
```

```
version: "3"

services:
  agent:
    image: grafana/agent:latest
    restart: always
    container_name: agent
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./agent.yml:/etc/agent-config/
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yml
    networks:
      - prometheus

networks:
  # Change this to "pterodactyl_nw" and external to true IF you are using Pterodactyl
  prometheus:
    external: true
```
