### ISSUE TITLE
Support PAPI for custom metrics

### ISSUE THREAD

**Issue by jippi** [Cubxity/UnifiedMetrics#53]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues before opening this bug report.

### Current Behavior

Not possible to use PAPI values for extracting metrics

### Expected Behavior

Being able to use PAPI values for custom metrics

I'm using https://www.spigotmc.org/resources/view-distance-tweaks-1-14-1-18.75164/ on my servers and would love to see the render/simulation distance over time vs MSPT

I'm sure there would be other great values in PAPI once I would start digging into them.

I think where this _might_ be more complicated than I initially thought is around some PAPI values being "per world" or "per X" - and likely wanting to either support a list that gets enumerated and emitted together, or some other way to provide different PAPI keys, but emit them as a single metric with tags

e.g. given `%viewdistancetweaks_simulation_distance_<world>%`  it could possibly be satisfied with custom config like this:

```
name: viewdistancetweaks_simulation_distance
papi: viewdistancetweaks_simulation_distance_<world>
values: 
  world: [world,world_the_end,world_nether]
tags:
  world: <world>
```

Where it would basically be

```
// compute all permutations of key/value combinations within the `values` dict
// iterate each of these and read PAPI value, generate metric, emit tags
// replacing `<world>` with each possible value in `values.world`  across `papi` and `tags`
```

### Server type

Spigot (includes Spigot-based forks)

### Server Version

1.18.1

### Other Mods / Plugins in your server

N/A

### Error log

N/A

### More information

N/A
